/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace MockMegapot {
      
    export type TicketStruct = {owner: AddressLike, purchaseTime: BigNumberish, claimed: boolean, drawId: BigNumberish, prizeAmount: BigNumberish}

    export type TicketStructOutput = [owner: string, purchaseTime: bigint, claimed: boolean, drawId: bigint, prizeAmount: bigint] & {owner: string, purchaseTime: bigint, claimed: boolean, drawId: bigint, prizeAmount: bigint }
  
    }

  export interface MockMegapotInterface extends Interface {
    getFunction(nameOrSignature: "BASIS_POINTS" | "addToJackpot" | "advanceDraw" | "buyTickets" | "checkWinners" | "claimPrizes" | "claimReferralEarnings" | "currentDrawId" | "getCurrentDrawId" | "getCurrentJackpot" | "getTicket" | "getTicketDetails" | "getTicketPrice" | "getTicketsByOwner" | "getUnclaimedWinnings" | "jackpotAmount" | "minTickets" | "paymentToken" | "referralBps" | "referralEarnings" | "setReferralBps" | "setTicketPrice" | "setWinningTicket" | "setWinningTickets" | "ticketIdCounter" | "ticketPrice" | "tickets"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DrawAdvanced" | "PrizesClaimed" | "TicketsPurchased" | "WinnerSet"): EventFragment;

    encodeFunctionData(functionFragment: 'BASIS_POINTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'addToJackpot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'advanceDraw', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyTickets', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'checkWinners', values: [BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'claimPrizes', values: [BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'claimReferralEarnings', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentDrawId', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCurrentDrawId', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCurrentJackpot', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTicket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTicketDetails', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTicketPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTicketsByOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUnclaimedWinnings', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'jackpotAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'minTickets', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'referralBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'referralEarnings', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setReferralBps', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTicketPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setWinningTicket', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setWinningTickets', values: [BigNumberish[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'ticketIdCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'ticketPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'tickets', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'BASIS_POINTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addToJackpot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'advanceDraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyTickets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkWinners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimPrizes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimReferralEarnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentDrawId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentDrawId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentJackpot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTicket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTicketDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTicketPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTicketsByOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUnclaimedWinnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jackpotAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minTickets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'referralBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'referralEarnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReferralBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTicketPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWinningTicket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWinningTickets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ticketIdCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ticketPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tickets', data: BytesLike): Result;
  }

  
    export namespace DrawAdvancedEvent {
      export type InputTuple = [oldDrawId: BigNumberish, newDrawId: BigNumberish, jackpot: BigNumberish];
      export type OutputTuple = [oldDrawId: bigint, newDrawId: bigint, jackpot: bigint];
      export interface OutputObject {oldDrawId: bigint, newDrawId: bigint, jackpot: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PrizesClaimedEvent {
      export type InputTuple = [winner: AddressLike, ticketIds: BigNumberish[], totalPrize: BigNumberish];
      export type OutputTuple = [winner: string, ticketIds: bigint[], totalPrize: bigint];
      export interface OutputObject {winner: string, ticketIds: bigint[], totalPrize: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketsPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, ticketIds: BigNumberish[], amount: BigNumberish, referrer: AddressLike, drawId: BigNumberish];
      export type OutputTuple = [buyer: string, ticketIds: bigint[], amount: bigint, referrer: string, drawId: bigint];
      export interface OutputObject {buyer: string, ticketIds: bigint[], amount: bigint, referrer: string, drawId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WinnerSetEvent {
      export type InputTuple = [ticketId: BigNumberish, prizeAmount: BigNumberish];
      export type OutputTuple = [ticketId: bigint, prizeAmount: bigint];
      export interface OutputObject {ticketId: bigint, prizeAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockMegapot extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockMegapot;
    waitForDeployment(): Promise<this>;

    interface: MockMegapotInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASIS_POINTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addToJackpot: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    advanceDraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    buyTickets: TypedContractMethod<
      [amount: BigNumberish, referrer: AddressLike, ],
      [bigint[]],
      'nonpayable'
    >
    

    
    checkWinners: TypedContractMethod<
      [ticketIds: BigNumberish[], ],
      [[boolean[], bigint[]] & {winningTickets: boolean[], prizes: bigint[] }],
      'view'
    >
    

    
    claimPrizes: TypedContractMethod<
      [ticketIds: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >
    

    
    claimReferralEarnings: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    currentDrawId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCurrentDrawId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCurrentJackpot: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTicket: TypedContractMethod<
      [ticketId: BigNumberish, ],
      [[string, bigint, boolean, bigint] & {owner: string, purchaseTime: bigint, claimed: boolean, drawId: bigint }],
      'view'
    >
    

    
    getTicketDetails: TypedContractMethod<
      [ticketId: BigNumberish, ],
      [MockMegapot.TicketStructOutput],
      'view'
    >
    

    
    getTicketPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTicketsByOwner: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getUnclaimedWinnings: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    jackpotAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    minTickets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    paymentToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    referralBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    referralEarnings: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    setReferralBps: TypedContractMethod<
      [_referralBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTicketPrice: TypedContractMethod<
      [_ticketPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setWinningTicket: TypedContractMethod<
      [ticketId: BigNumberish, prizeAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setWinningTickets: TypedContractMethod<
      [ticketIds: BigNumberish[], prizeAmounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    ticketIdCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ticketPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tickets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, boolean, bigint, bigint] & {owner: string, purchaseTime: bigint, claimed: boolean, drawId: bigint, prizeAmount: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASIS_POINTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addToJackpot'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'advanceDraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buyTickets'): TypedContractMethod<
      [amount: BigNumberish, referrer: AddressLike, ],
      [bigint[]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkWinners'): TypedContractMethod<
      [ticketIds: BigNumberish[], ],
      [[boolean[], bigint[]] & {winningTickets: boolean[], prizes: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'claimPrizes'): TypedContractMethod<
      [ticketIds: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimReferralEarnings'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'currentDrawId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCurrentDrawId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCurrentJackpot'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTicket'): TypedContractMethod<
      [ticketId: BigNumberish, ],
      [[string, bigint, boolean, bigint] & {owner: string, purchaseTime: bigint, claimed: boolean, drawId: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTicketDetails'): TypedContractMethod<
      [ticketId: BigNumberish, ],
      [MockMegapot.TicketStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTicketPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTicketsByOwner'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getUnclaimedWinnings'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'jackpotAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minTickets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'paymentToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'referralBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'referralEarnings'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setReferralBps'): TypedContractMethod<
      [_referralBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTicketPrice'): TypedContractMethod<
      [_ticketPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWinningTicket'): TypedContractMethod<
      [ticketId: BigNumberish, prizeAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWinningTickets'): TypedContractMethod<
      [ticketIds: BigNumberish[], prizeAmounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ticketIdCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ticketPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tickets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, boolean, bigint, bigint] & {owner: string, purchaseTime: bigint, claimed: boolean, drawId: bigint, prizeAmount: bigint }],
      'view'
    >;

    getEvent(key: 'DrawAdvanced'): TypedContractEvent<DrawAdvancedEvent.InputTuple, DrawAdvancedEvent.OutputTuple, DrawAdvancedEvent.OutputObject>;
getEvent(key: 'PrizesClaimed'): TypedContractEvent<PrizesClaimedEvent.InputTuple, PrizesClaimedEvent.OutputTuple, PrizesClaimedEvent.OutputObject>;
getEvent(key: 'TicketsPurchased'): TypedContractEvent<TicketsPurchasedEvent.InputTuple, TicketsPurchasedEvent.OutputTuple, TicketsPurchasedEvent.OutputObject>;
getEvent(key: 'WinnerSet'): TypedContractEvent<WinnerSetEvent.InputTuple, WinnerSetEvent.OutputTuple, WinnerSetEvent.OutputObject>;

    filters: {
      
      'DrawAdvanced(uint256,uint256,uint256)': TypedContractEvent<DrawAdvancedEvent.InputTuple, DrawAdvancedEvent.OutputTuple, DrawAdvancedEvent.OutputObject>;
      DrawAdvanced: TypedContractEvent<DrawAdvancedEvent.InputTuple, DrawAdvancedEvent.OutputTuple, DrawAdvancedEvent.OutputObject>;
    

      'PrizesClaimed(address,uint256[],uint256)': TypedContractEvent<PrizesClaimedEvent.InputTuple, PrizesClaimedEvent.OutputTuple, PrizesClaimedEvent.OutputObject>;
      PrizesClaimed: TypedContractEvent<PrizesClaimedEvent.InputTuple, PrizesClaimedEvent.OutputTuple, PrizesClaimedEvent.OutputObject>;
    

      'TicketsPurchased(address,uint256[],uint256,address,uint256)': TypedContractEvent<TicketsPurchasedEvent.InputTuple, TicketsPurchasedEvent.OutputTuple, TicketsPurchasedEvent.OutputObject>;
      TicketsPurchased: TypedContractEvent<TicketsPurchasedEvent.InputTuple, TicketsPurchasedEvent.OutputTuple, TicketsPurchasedEvent.OutputObject>;
    

      'WinnerSet(uint256,uint256)': TypedContractEvent<WinnerSetEvent.InputTuple, WinnerSetEvent.OutputTuple, WinnerSetEvent.OutputObject>;
      WinnerSet: TypedContractEvent<WinnerSetEvent.InputTuple, WinnerSetEvent.OutputTuple, WinnerSetEvent.OutputObject>;
    
    };
  }