/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMegapot__factory } from './IMegapot__factory.js';
export { IMegapotReferral__factory } from './IMegapotReferral__factory.js';