/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface LotteryAdapterInterface extends Interface {
    getFunction(nameOrSignature: "BASIS_POINTS" | "BUILDING_TYPE" | "MAX_FEE_BPS" | "calculateFee" | "core" | "estimateYield" | "getBuildingType" | "getPlacementFee" | "getRequiredProtocols" | "getTreasury" | "megapot" | "owner" | "placementFeeBps" | "prepareDemolish" | "prepareHarvest" | "preparePlace" | "renounceOwnership" | "setMegapot" | "setPlacementFee" | "setTreasury" | "setUSDC" | "transferOwnership" | "treasury" | "usdc" | "validatePlacement"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MegapotUpdated" | "OwnershipTransferred" | "PlacementFeeUpdated" | "TreasuryUpdated" | "USDCUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'BASIS_POINTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'BUILDING_TYPE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'calculateFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'core', values?: undefined): string;
encodeFunctionData(functionFragment: 'estimateYield', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBuildingType', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPlacementFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRequiredProtocols', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'megapot', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'placementFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'prepareDemolish', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'prepareHarvest', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'preparePlace', values: [AddressLike, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMegapot', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPlacementFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setUSDC', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'validatePlacement', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'BASIS_POINTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BUILDING_TYPE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'core', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'estimateYield', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBuildingType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlacementFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequiredProtocols', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'megapot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placementFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prepareDemolish', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prepareHarvest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'preparePlace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMegapot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPlacementFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUSDC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validatePlacement', data: BytesLike): Result;
  }

  
    export namespace MegapotUpdatedEvent {
      export type InputTuple = [megapot: AddressLike];
      export type OutputTuple = [megapot: string];
      export interface OutputObject {megapot: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlacementFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryUpdatedEvent {
      export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
      export type OutputTuple = [oldTreasury: string, newTreasury: string];
      export interface OutputObject {oldTreasury: string, newTreasury: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace USDCUpdatedEvent {
      export type InputTuple = [usdc: AddressLike];
      export type OutputTuple = [usdc: string];
      export interface OutputObject {usdc: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LotteryAdapter extends BaseContract {
    
    connect(runner?: ContractRunner | null): LotteryAdapter;
    waitForDeployment(): Promise<this>;

    interface: LotteryAdapterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASIS_POINTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BUILDING_TYPE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    calculateFee: TypedContractMethod<
      [amount: BigNumberish, ],
      [[bigint, bigint] & {feeAmount: bigint, netAmount: bigint }],
      'view'
    >
    

    
    core: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    estimateYield: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string] & {estimatedYield: bigint, yieldAsset: string }],
      'view'
    >
    

    
    getBuildingType: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getPlacementFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRequiredProtocols: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getTreasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    megapot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    placementFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    prepareDemolish: TypedContractMethod<
      [user: AddressLike, arg1: AddressLike, buildingId: BigNumberish, arg3: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >
    

    
    prepareHarvest: TypedContractMethod<
      [user: AddressLike, arg1: AddressLike, buildingId: BigNumberish, params: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >
    

    
    preparePlace: TypedContractMethod<
      [user: AddressLike, arg1: AddressLike, params: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setMegapot: TypedContractMethod<
      [_megapot: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPlacementFee: TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setUSDC: TypedContractMethod<
      [_usdc: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    validatePlacement: TypedContractMethod<
      [params: BytesLike, ],
      [[boolean, string] & {isValid: boolean, reason: string }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASIS_POINTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BUILDING_TYPE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateFee'): TypedContractMethod<
      [amount: BigNumberish, ],
      [[bigint, bigint] & {feeAmount: bigint, netAmount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'core'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'estimateYield'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string] & {estimatedYield: bigint, yieldAsset: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getBuildingType'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPlacementFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRequiredProtocols'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTreasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'megapot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'placementFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'prepareDemolish'): TypedContractMethod<
      [user: AddressLike, arg1: AddressLike, buildingId: BigNumberish, arg3: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'prepareHarvest'): TypedContractMethod<
      [user: AddressLike, arg1: AddressLike, buildingId: BigNumberish, params: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'preparePlace'): TypedContractMethod<
      [user: AddressLike, arg1: AddressLike, params: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMegapot'): TypedContractMethod<
      [_megapot: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPlacementFee'): TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUSDC'): TypedContractMethod<
      [_usdc: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'validatePlacement'): TypedContractMethod<
      [params: BytesLike, ],
      [[boolean, string] & {isValid: boolean, reason: string }],
      'view'
    >;

    getEvent(key: 'MegapotUpdated'): TypedContractEvent<MegapotUpdatedEvent.InputTuple, MegapotUpdatedEvent.OutputTuple, MegapotUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PlacementFeeUpdated'): TypedContractEvent<PlacementFeeUpdatedEvent.InputTuple, PlacementFeeUpdatedEvent.OutputTuple, PlacementFeeUpdatedEvent.OutputObject>;
getEvent(key: 'TreasuryUpdated'): TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
getEvent(key: 'USDCUpdated'): TypedContractEvent<USDCUpdatedEvent.InputTuple, USDCUpdatedEvent.OutputTuple, USDCUpdatedEvent.OutputObject>;

    filters: {
      
      'MegapotUpdated(address)': TypedContractEvent<MegapotUpdatedEvent.InputTuple, MegapotUpdatedEvent.OutputTuple, MegapotUpdatedEvent.OutputObject>;
      MegapotUpdated: TypedContractEvent<MegapotUpdatedEvent.InputTuple, MegapotUpdatedEvent.OutputTuple, MegapotUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PlacementFeeUpdated(uint256,uint256)': TypedContractEvent<PlacementFeeUpdatedEvent.InputTuple, PlacementFeeUpdatedEvent.OutputTuple, PlacementFeeUpdatedEvent.OutputObject>;
      PlacementFeeUpdated: TypedContractEvent<PlacementFeeUpdatedEvent.InputTuple, PlacementFeeUpdatedEvent.OutputTuple, PlacementFeeUpdatedEvent.OutputObject>;
    

      'TreasuryUpdated(address,address)': TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
      TreasuryUpdated: TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
    

      'USDCUpdated(address)': TypedContractEvent<USDCUpdatedEvent.InputTuple, USDCUpdatedEvent.OutputTuple, USDCUpdatedEvent.OutputObject>;
      USDCUpdated: TypedContractEvent<USDCUpdatedEvent.InputTuple, USDCUpdatedEvent.OutputTuple, USDCUpdatedEvent.OutputObject>;
    
    };
  }