/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IMegapotReferralInterface extends Interface {
    getFunction(nameOrSignature: "claimReferralEarnings" | "getReferralCode" | "getReferralEarnings" | "registerReferrer"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'claimReferralEarnings', values?: undefined): string;
encodeFunctionData(functionFragment: 'getReferralCode', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReferralEarnings', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerReferrer', values: [string]): string;

    decodeFunctionResult(functionFragment: 'claimReferralEarnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReferralCode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReferralEarnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerReferrer', data: BytesLike): Result;
  }

  

  export interface IMegapotReferral extends BaseContract {
    
    connect(runner?: ContractRunner | null): IMegapotReferral;
    waitForDeployment(): Promise<this>;

    interface: IMegapotReferralInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claimReferralEarnings: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getReferralCode: TypedContractMethod<
      [referrer: AddressLike, ],
      [string],
      'view'
    >
    

    
    getReferralEarnings: TypedContractMethod<
      [referrer: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    registerReferrer: TypedContractMethod<
      [referralCode: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claimReferralEarnings'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getReferralCode'): TypedContractMethod<
      [referrer: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getReferralEarnings'): TypedContractMethod<
      [referrer: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerReferrer'): TypedContractMethod<
      [referralCode: string, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }