/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IAerodromeRouterInterface extends Interface {
    getFunction(nameOrSignature: "addLiquidity" | "factory" | "pairFor" | "quoteLiquidity" | "removeLiquidity"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'addLiquidity', values: [AddressLike, AddressLike, boolean, BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'pairFor', values: [AddressLike, AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'quoteLiquidity', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeLiquidity', values: [AddressLike, AddressLike, boolean, BigNumberish, BigNumberish, BigNumberish, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pairFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeLiquidity', data: BytesLike): Result;
  }

  

  export interface IAerodromeRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): IAerodromeRouter;
    waitForDeployment(): Promise<this>;

    interface: IAerodromeRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addLiquidity: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, stable: boolean, amountADesired: BigNumberish, amountBDesired: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint, bigint] & {amountA: bigint, amountB: bigint, liquidity: bigint }],
      'nonpayable'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pairFor: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, stable: boolean, ],
      [string],
      'view'
    >
    

    
    quoteLiquidity: TypedContractMethod<
      [amountA: BigNumberish, reserveA: BigNumberish, reserveB: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    removeLiquidity: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, stable: boolean, liquidity: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint] & {amountA: bigint, amountB: bigint }],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, stable: boolean, amountADesired: BigNumberish, amountBDesired: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint, bigint] & {amountA: bigint, amountB: bigint, liquidity: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pairFor'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, stable: boolean, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'quoteLiquidity'): TypedContractMethod<
      [amountA: BigNumberish, reserveA: BigNumberish, reserveB: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'removeLiquidity'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, stable: boolean, liquidity: BigNumberish, amountAMin: BigNumberish, amountBMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint] & {amountA: bigint, amountB: bigint }],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }