/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IBuildingAdapterInterface extends Interface {
    getFunction(nameOrSignature: "calculateFee" | "estimateYield" | "getBuildingType" | "getPlacementFee" | "getRequiredProtocols" | "getTreasury" | "prepareDemolish" | "prepareHarvest" | "preparePlace" | "validatePlacement"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'calculateFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'estimateYield', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBuildingType', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPlacementFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRequiredProtocols', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'prepareDemolish', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'prepareHarvest', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'preparePlace', values: [AddressLike, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'validatePlacement', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'calculateFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'estimateYield', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBuildingType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlacementFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequiredProtocols', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prepareDemolish', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prepareHarvest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'preparePlace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validatePlacement', data: BytesLike): Result;
  }

  

  export interface IBuildingAdapter extends BaseContract {
    
    connect(runner?: ContractRunner | null): IBuildingAdapter;
    waitForDeployment(): Promise<this>;

    interface: IBuildingAdapterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    calculateFee: TypedContractMethod<
      [amount: BigNumberish, ],
      [[bigint, bigint] & {feeAmount: bigint, netAmount: bigint }],
      'view'
    >
    

    
    estimateYield: TypedContractMethod<
      [buildingId: BigNumberish, ],
      [[bigint, string] & {estimatedYield: bigint, yieldAsset: string }],
      'view'
    >
    

    
    getBuildingType: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getPlacementFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRequiredProtocols: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getTreasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    prepareDemolish: TypedContractMethod<
      [user: AddressLike, userSmartWallet: AddressLike, buildingId: BigNumberish, params: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >
    

    
    prepareHarvest: TypedContractMethod<
      [user: AddressLike, userSmartWallet: AddressLike, buildingId: BigNumberish, params: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >
    

    
    preparePlace: TypedContractMethod<
      [user: AddressLike, userSmartWallet: AddressLike, params: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >
    

    
    validatePlacement: TypedContractMethod<
      [params: BytesLike, ],
      [[boolean, string] & {isValid: boolean, reason: string }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'calculateFee'): TypedContractMethod<
      [amount: BigNumberish, ],
      [[bigint, bigint] & {feeAmount: bigint, netAmount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'estimateYield'): TypedContractMethod<
      [buildingId: BigNumberish, ],
      [[bigint, string] & {estimatedYield: bigint, yieldAsset: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getBuildingType'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPlacementFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRequiredProtocols'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTreasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'prepareDemolish'): TypedContractMethod<
      [user: AddressLike, userSmartWallet: AddressLike, buildingId: BigNumberish, params: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'prepareHarvest'): TypedContractMethod<
      [user: AddressLike, userSmartWallet: AddressLike, buildingId: BigNumberish, params: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'preparePlace'): TypedContractMethod<
      [user: AddressLike, userSmartWallet: AddressLike, params: BytesLike, ],
      [[string[], bigint[], string[]] & {targets: string[], values: bigint[], datas: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'validatePlacement'): TypedContractMethod<
      [params: BytesLike, ],
      [[boolean, string] & {isValid: boolean, reason: string }],
      'view'
    >;

    

    filters: {
      
    };
  }