/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAccountSol from './IAccount.sol/index.js';
export type { iAccountSol };
import type * as iAerodromeRouterSol from './IAerodromeRouter.sol/index.js';
export type { iAerodromeRouterSol };
import type * as iEntryPointSol from './IEntryPoint.sol/index.js';
export type { iEntryPointSol };
import type * as iMegapotSol from './IMegapot.sol/index.js';
export type { iMegapotSol };
export type { IAToken } from './IAToken.js';
export type { IAavePool } from './IAavePool.js';
export type { IBuildingAdapter } from './IBuildingAdapter.js';