/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace DefiCityCore {
      
    export type BuildingStruct = {id: BigNumberish, owner: AddressLike, smartWallet: AddressLike, buildingType: string, asset: AddressLike, amount: BigNumberish, placedAt: BigNumberish, coordinateX: BigNumberish, coordinateY: BigNumberish, active: boolean, metadata: BytesLike}

    export type BuildingStructOutput = [id: bigint, owner: string, smartWallet: string, buildingType: string, asset: string, amount: bigint, placedAt: bigint, coordinateX: bigint, coordinateY: bigint, active: boolean, metadata: string] & {id: bigint, owner: string, smartWallet: string, buildingType: string, asset: string, amount: bigint, placedAt: bigint, coordinateX: bigint, coordinateY: bigint, active: boolean, metadata: string }
  

    export type UserStatsStruct = {totalDeposited: BigNumberish, totalWithdrawn: BigNumberish, totalHarvested: BigNumberish, buildingCount: BigNumberish, cityCreatedAt: BigNumberish}

    export type UserStatsStructOutput = [totalDeposited: bigint, totalWithdrawn: bigint, totalHarvested: bigint, buildingCount: bigint, cityCreatedAt: bigint] & {totalDeposited: bigint, totalWithdrawn: bigint, totalHarvested: bigint, buildingCount: bigint, cityCreatedAt: bigint }
  
    }

  export interface DefiCityCoreInterface extends Interface {
    getFunction(nameOrSignature: "ASSET_MANAGER_ROLE" | "DEFAULT_ADMIN_ROLE" | "EMERGENCY_ROLE" | "MAX_FEE_BPS" | "MODULE_MANAGER_ROLE" | "PAUSER_ROLE" | "addSupportedAsset" | "buildingIdCounter" | "buildingManager" | "buildings" | "createTownHall" | "emergencyManager" | "feeManager" | "getBuildingAt" | "getRoleAdmin" | "getUserBuildings" | "getUserStats" | "getWallet" | "grantRole" | "hasRole" | "hasWallet" | "owner" | "pause" | "paused" | "recordBuildingPlacement" | "recordDemolition" | "recordDeposit" | "recordHarvest" | "recordWithdrawal" | "registerWallet" | "removeSupportedAsset" | "renounceOwnership" | "renounceRole" | "revokeRole" | "setModules" | "setTreasury" | "setWalletFactory" | "supportedAssets" | "supportsInterface" | "transferOwnership" | "treasury" | "unpause" | "userBuildings" | "userGridBuildings" | "userSmartWallets" | "userStats" | "walletFactory" | "walletToOwner"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AssetAdded" | "AssetRemoved" | "BuildingDemolished" | "BuildingPlaced" | "DepositRecorded" | "FactoryUpdated" | "Harvested" | "ModulesUpdated" | "OwnershipTransferred" | "Paused" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused" | "WalletRegistered" | "WithdrawalRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'ASSET_MANAGER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'EMERGENCY_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MODULE_MANAGER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'addSupportedAsset', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'buildingIdCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'buildingManager', values?: undefined): string;
encodeFunctionData(functionFragment: 'buildings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createTownHall', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'emergencyManager', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeManager', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBuildingAt', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getUserBuildings', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserStats', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordBuildingPlacement', values: [AddressLike, string, AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'recordDemolition', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordDeposit', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordHarvest', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordWithdrawal', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerWallet', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'removeSupportedAsset', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setModules', values: [AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setWalletFactory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportedAssets', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'userBuildings', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'userGridBuildings', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'userSmartWallets', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userStats', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'walletFactory', values?: undefined): string;
encodeFunctionData(functionFragment: 'walletToOwner', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'ASSET_MANAGER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'EMERGENCY_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MODULE_MANAGER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addSupportedAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buildingIdCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buildingManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buildings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTownHall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBuildingAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserBuildings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordBuildingPlacement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordDemolition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordHarvest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordWithdrawal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeSupportedAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setModules', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWalletFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportedAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userBuildings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userGridBuildings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userSmartWallets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'walletFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'walletToOwner', data: BytesLike): Result;
  }

  
    export namespace AssetAddedEvent {
      export type InputTuple = [asset: AddressLike];
      export type OutputTuple = [asset: string];
      export interface OutputObject {asset: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AssetRemovedEvent {
      export type InputTuple = [asset: AddressLike];
      export type OutputTuple = [asset: string];
      export interface OutputObject {asset: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BuildingDemolishedEvent {
      export type InputTuple = [buildingId: BigNumberish, user: AddressLike, returnedAmount: BigNumberish];
      export type OutputTuple = [buildingId: bigint, user: string, returnedAmount: bigint];
      export interface OutputObject {buildingId: bigint, user: string, returnedAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BuildingPlacedEvent {
      export type InputTuple = [buildingId: BigNumberish, user: AddressLike, smartWallet: AddressLike, buildingType: string, asset: AddressLike, amount: BigNumberish, x: BigNumberish, y: BigNumberish];
      export type OutputTuple = [buildingId: bigint, user: string, smartWallet: string, buildingType: string, asset: string, amount: bigint, x: bigint, y: bigint];
      export interface OutputObject {buildingId: bigint, user: string, smartWallet: string, buildingType: string, asset: string, amount: bigint, x: bigint, y: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositRecordedEvent {
      export type InputTuple = [user: AddressLike, asset: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, asset: string, amount: bigint];
      export interface OutputObject {user: string, asset: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FactoryUpdatedEvent {
      export type InputTuple = [walletFactory: AddressLike];
      export type OutputTuple = [walletFactory: string];
      export interface OutputObject {walletFactory: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HarvestedEvent {
      export type InputTuple = [buildingId: BigNumberish, user: AddressLike, yieldAmount: BigNumberish];
      export type OutputTuple = [buildingId: bigint, user: string, yieldAmount: bigint];
      export interface OutputObject {buildingId: bigint, user: string, yieldAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModulesUpdatedEvent {
      export type InputTuple = [buildingManager: AddressLike, feeManager: AddressLike, emergencyManager: AddressLike];
      export type OutputTuple = [buildingManager: string, feeManager: string, emergencyManager: string];
      export interface OutputObject {buildingManager: string, feeManager: string, emergencyManager: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WalletRegisteredEvent {
      export type InputTuple = [user: AddressLike, smartWallet: AddressLike];
      export type OutputTuple = [user: string, smartWallet: string];
      export interface OutputObject {user: string, smartWallet: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalRecordedEvent {
      export type InputTuple = [user: AddressLike, asset: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, asset: string, amount: bigint];
      export interface OutputObject {user: string, asset: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DefiCityCore extends BaseContract {
    
    connect(runner?: ContractRunner | null): DefiCityCore;
    waitForDeployment(): Promise<this>;

    interface: DefiCityCoreInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ASSET_MANAGER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    EMERGENCY_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MODULE_MANAGER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addSupportedAsset: TypedContractMethod<
      [asset: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    buildingIdCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buildingManager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    buildings: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, string, bigint, bigint, bigint, bigint, boolean, string] & {id: bigint, owner: string, smartWallet: string, buildingType: string, asset: string, amount: bigint, placedAt: bigint, coordinateX: bigint, coordinateY: bigint, active: boolean, metadata: string }],
      'view'
    >
    

    
    createTownHall: TypedContractMethod<
      [x: BigNumberish, y: BigNumberish, ],
      [[string, bigint] & {walletAddress: string, buildingId: bigint }],
      'nonpayable'
    >
    

    
    emergencyManager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    feeManager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getBuildingAt: TypedContractMethod<
      [user: AddressLike, x: BigNumberish, y: BigNumberish, ],
      [DefiCityCore.BuildingStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getUserBuildings: TypedContractMethod<
      [user: AddressLike, ],
      [DefiCityCore.BuildingStructOutput[]],
      'view'
    >
    

    
    getUserStats: TypedContractMethod<
      [user: AddressLike, ],
      [DefiCityCore.UserStatsStructOutput],
      'view'
    >
    

    
    getWallet: TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hasWallet: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    recordBuildingPlacement: TypedContractMethod<
      [user: AddressLike, buildingType: string, asset: AddressLike, amount: BigNumberish, x: BigNumberish, y: BigNumberish, metadata: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    recordDemolition: TypedContractMethod<
      [user: AddressLike, buildingId: BigNumberish, returnedAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordDeposit: TypedContractMethod<
      [user: AddressLike, asset: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordHarvest: TypedContractMethod<
      [user: AddressLike, buildingId: BigNumberish, yieldAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordWithdrawal: TypedContractMethod<
      [user: AddressLike, asset: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerWallet: TypedContractMethod<
      [user: AddressLike, smartWallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeSupportedAsset: TypedContractMethod<
      [asset: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setModules: TypedContractMethod<
      [_buildingManager: AddressLike, _feeManager: AddressLike, _emergencyManager: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [_treasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setWalletFactory: TypedContractMethod<
      [_walletFactory: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportedAssets: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    userBuildings: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    userGridBuildings: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    userSmartWallets: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    userStats: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {totalDeposited: bigint, totalWithdrawn: bigint, totalHarvested: bigint, buildingCount: bigint, cityCreatedAt: bigint }],
      'view'
    >
    

    
    walletFactory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    walletToOwner: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ASSET_MANAGER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'EMERGENCY_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MODULE_MANAGER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addSupportedAsset'): TypedContractMethod<
      [asset: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buildingIdCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buildingManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'buildings'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, string, bigint, bigint, bigint, bigint, boolean, string] & {id: bigint, owner: string, smartWallet: string, buildingType: string, asset: string, amount: bigint, placedAt: bigint, coordinateX: bigint, coordinateY: bigint, active: boolean, metadata: string }],
      'view'
    >;
getFunction(nameOrSignature: 'createTownHall'): TypedContractMethod<
      [x: BigNumberish, y: BigNumberish, ],
      [[string, bigint] & {walletAddress: string, buildingId: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'feeManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBuildingAt'): TypedContractMethod<
      [user: AddressLike, x: BigNumberish, y: BigNumberish, ],
      [DefiCityCore.BuildingStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getUserBuildings'): TypedContractMethod<
      [user: AddressLike, ],
      [DefiCityCore.BuildingStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getUserStats'): TypedContractMethod<
      [user: AddressLike, ],
      [DefiCityCore.UserStatsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getWallet'): TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasWallet'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordBuildingPlacement'): TypedContractMethod<
      [user: AddressLike, buildingType: string, asset: AddressLike, amount: BigNumberish, x: BigNumberish, y: BigNumberish, metadata: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordDemolition'): TypedContractMethod<
      [user: AddressLike, buildingId: BigNumberish, returnedAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordDeposit'): TypedContractMethod<
      [user: AddressLike, asset: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordHarvest'): TypedContractMethod<
      [user: AddressLike, buildingId: BigNumberish, yieldAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordWithdrawal'): TypedContractMethod<
      [user: AddressLike, asset: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerWallet'): TypedContractMethod<
      [user: AddressLike, smartWallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeSupportedAsset'): TypedContractMethod<
      [asset: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setModules'): TypedContractMethod<
      [_buildingManager: AddressLike, _feeManager: AddressLike, _emergencyManager: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [_treasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWalletFactory'): TypedContractMethod<
      [_walletFactory: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportedAssets'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userBuildings'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userGridBuildings'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userSmartWallets'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'userStats'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {totalDeposited: bigint, totalWithdrawn: bigint, totalHarvested: bigint, buildingCount: bigint, cityCreatedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'walletFactory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'walletToOwner'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;

    getEvent(key: 'AssetAdded'): TypedContractEvent<AssetAddedEvent.InputTuple, AssetAddedEvent.OutputTuple, AssetAddedEvent.OutputObject>;
getEvent(key: 'AssetRemoved'): TypedContractEvent<AssetRemovedEvent.InputTuple, AssetRemovedEvent.OutputTuple, AssetRemovedEvent.OutputObject>;
getEvent(key: 'BuildingDemolished'): TypedContractEvent<BuildingDemolishedEvent.InputTuple, BuildingDemolishedEvent.OutputTuple, BuildingDemolishedEvent.OutputObject>;
getEvent(key: 'BuildingPlaced'): TypedContractEvent<BuildingPlacedEvent.InputTuple, BuildingPlacedEvent.OutputTuple, BuildingPlacedEvent.OutputObject>;
getEvent(key: 'DepositRecorded'): TypedContractEvent<DepositRecordedEvent.InputTuple, DepositRecordedEvent.OutputTuple, DepositRecordedEvent.OutputObject>;
getEvent(key: 'FactoryUpdated'): TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
getEvent(key: 'Harvested'): TypedContractEvent<HarvestedEvent.InputTuple, HarvestedEvent.OutputTuple, HarvestedEvent.OutputObject>;
getEvent(key: 'ModulesUpdated'): TypedContractEvent<ModulesUpdatedEvent.InputTuple, ModulesUpdatedEvent.OutputTuple, ModulesUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'WalletRegistered'): TypedContractEvent<WalletRegisteredEvent.InputTuple, WalletRegisteredEvent.OutputTuple, WalletRegisteredEvent.OutputObject>;
getEvent(key: 'WithdrawalRecorded'): TypedContractEvent<WithdrawalRecordedEvent.InputTuple, WithdrawalRecordedEvent.OutputTuple, WithdrawalRecordedEvent.OutputObject>;

    filters: {
      
      'AssetAdded(address)': TypedContractEvent<AssetAddedEvent.InputTuple, AssetAddedEvent.OutputTuple, AssetAddedEvent.OutputObject>;
      AssetAdded: TypedContractEvent<AssetAddedEvent.InputTuple, AssetAddedEvent.OutputTuple, AssetAddedEvent.OutputObject>;
    

      'AssetRemoved(address)': TypedContractEvent<AssetRemovedEvent.InputTuple, AssetRemovedEvent.OutputTuple, AssetRemovedEvent.OutputObject>;
      AssetRemoved: TypedContractEvent<AssetRemovedEvent.InputTuple, AssetRemovedEvent.OutputTuple, AssetRemovedEvent.OutputObject>;
    

      'BuildingDemolished(uint256,address,uint256)': TypedContractEvent<BuildingDemolishedEvent.InputTuple, BuildingDemolishedEvent.OutputTuple, BuildingDemolishedEvent.OutputObject>;
      BuildingDemolished: TypedContractEvent<BuildingDemolishedEvent.InputTuple, BuildingDemolishedEvent.OutputTuple, BuildingDemolishedEvent.OutputObject>;
    

      'BuildingPlaced(uint256,address,address,string,address,uint256,uint256,uint256)': TypedContractEvent<BuildingPlacedEvent.InputTuple, BuildingPlacedEvent.OutputTuple, BuildingPlacedEvent.OutputObject>;
      BuildingPlaced: TypedContractEvent<BuildingPlacedEvent.InputTuple, BuildingPlacedEvent.OutputTuple, BuildingPlacedEvent.OutputObject>;
    

      'DepositRecorded(address,address,uint256)': TypedContractEvent<DepositRecordedEvent.InputTuple, DepositRecordedEvent.OutputTuple, DepositRecordedEvent.OutputObject>;
      DepositRecorded: TypedContractEvent<DepositRecordedEvent.InputTuple, DepositRecordedEvent.OutputTuple, DepositRecordedEvent.OutputObject>;
    

      'FactoryUpdated(address)': TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
      FactoryUpdated: TypedContractEvent<FactoryUpdatedEvent.InputTuple, FactoryUpdatedEvent.OutputTuple, FactoryUpdatedEvent.OutputObject>;
    

      'Harvested(uint256,address,uint256)': TypedContractEvent<HarvestedEvent.InputTuple, HarvestedEvent.OutputTuple, HarvestedEvent.OutputObject>;
      Harvested: TypedContractEvent<HarvestedEvent.InputTuple, HarvestedEvent.OutputTuple, HarvestedEvent.OutputObject>;
    

      'ModulesUpdated(address,address,address)': TypedContractEvent<ModulesUpdatedEvent.InputTuple, ModulesUpdatedEvent.OutputTuple, ModulesUpdatedEvent.OutputObject>;
      ModulesUpdated: TypedContractEvent<ModulesUpdatedEvent.InputTuple, ModulesUpdatedEvent.OutputTuple, ModulesUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'WalletRegistered(address,address)': TypedContractEvent<WalletRegisteredEvent.InputTuple, WalletRegisteredEvent.OutputTuple, WalletRegisteredEvent.OutputObject>;
      WalletRegistered: TypedContractEvent<WalletRegisteredEvent.InputTuple, WalletRegisteredEvent.OutputTuple, WalletRegisteredEvent.OutputObject>;
    

      'WithdrawalRecorded(address,address,uint256)': TypedContractEvent<WithdrawalRecordedEvent.InputTuple, WithdrawalRecordedEvent.OutputTuple, WithdrawalRecordedEvent.OutputObject>;
      WithdrawalRecorded: TypedContractEvent<WithdrawalRecordedEvent.InputTuple, WithdrawalRecordedEvent.OutputTuple, WithdrawalRecordedEvent.OutputObject>;
    
    };
  }