/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'BankAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BankAdapter__factory>
getContractFactory(name: 'LotteryAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LotteryAdapter__factory>
getContractFactory(name: 'ShopAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ShopAdapter__factory>
getContractFactory(name: 'BuildingRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BuildingRegistry__factory>
getContractFactory(name: 'DefiCityCore', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DefiCityCore__factory>
getContractFactory(name: 'WalletFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.WalletFactory__factory>
getContractFactory(name: 'IAToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAToken__factory>
getContractFactory(name: 'IAavePool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAavePool__factory>
getContractFactory(name: 'IAccount', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAccount__factory>
getContractFactory(name: 'IAccountExecute', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAccountExecute__factory>
getContractFactory(name: 'IAccountInitialize', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAccountInitialize__factory>
getContractFactory(name: 'IAerodromeGauge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAerodromeGauge__factory>
getContractFactory(name: 'IAerodromePair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAerodromePair__factory>
getContractFactory(name: 'IAerodromeRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAerodromeRouter__factory>
getContractFactory(name: 'IBuildingAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IBuildingAdapter__factory>
getContractFactory(name: 'IEntryPoint', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEntryPoint__factory>
getContractFactory(name: 'IStakeManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStakeManager__factory>
getContractFactory(name: 'IMegapot', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMegapot__factory>
getContractFactory(name: 'IMegapotReferral', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMegapotReferral__factory>
getContractFactory(name: 'MockAavePool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockAavePool__factory>
getContractFactory(name: 'MockAerodromeGauge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockAerodromeGauge__factory>
getContractFactory(name: 'MockAerodromePair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockAerodromePair__factory>
getContractFactory(name: 'MockAerodromeRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockAerodromeRouter__factory>
getContractFactory(name: 'MockEntryPoint', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockEntryPoint__factory>
getContractFactory(name: 'MockMegapot', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockMegapot__factory>
getContractFactory(name: 'SmartWallet', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SmartWallet__factory>

  getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'BankAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BankAdapter>
getContractAt(name: 'LotteryAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LotteryAdapter>
getContractAt(name: 'ShopAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ShopAdapter>
getContractAt(name: 'BuildingRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BuildingRegistry>
getContractAt(name: 'DefiCityCore', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DefiCityCore>
getContractAt(name: 'WalletFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.WalletFactory>
getContractAt(name: 'IAToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAToken>
getContractAt(name: 'IAavePool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAavePool>
getContractAt(name: 'IAccount', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAccount>
getContractAt(name: 'IAccountExecute', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAccountExecute>
getContractAt(name: 'IAccountInitialize', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAccountInitialize>
getContractAt(name: 'IAerodromeGauge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAerodromeGauge>
getContractAt(name: 'IAerodromePair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAerodromePair>
getContractAt(name: 'IAerodromeRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAerodromeRouter>
getContractAt(name: 'IBuildingAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IBuildingAdapter>
getContractAt(name: 'IEntryPoint', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEntryPoint>
getContractAt(name: 'IStakeManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStakeManager>
getContractAt(name: 'IMegapot', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMegapot>
getContractAt(name: 'IMegapotReferral', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMegapotReferral>
getContractAt(name: 'MockAavePool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockAavePool>
getContractAt(name: 'MockAerodromeGauge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockAerodromeGauge>
getContractAt(name: 'MockAerodromePair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockAerodromePair>
getContractAt(name: 'MockAerodromeRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockAerodromeRouter>
getContractAt(name: 'MockEntryPoint', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockEntryPoint>
getContractAt(name: 'MockMegapot', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockMegapot>
getContractAt(name: 'SmartWallet', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SmartWallet>

  deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'BankAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BankAdapter>
deployContract(name: 'LotteryAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LotteryAdapter>
deployContract(name: 'ShopAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ShopAdapter>
deployContract(name: 'BuildingRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BuildingRegistry>
deployContract(name: 'DefiCityCore', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DefiCityCore>
deployContract(name: 'WalletFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WalletFactory>
deployContract(name: 'IAToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAToken>
deployContract(name: 'IAavePool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAavePool>
deployContract(name: 'IAccount', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccount>
deployContract(name: 'IAccountExecute', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccountExecute>
deployContract(name: 'IAccountInitialize', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccountInitialize>
deployContract(name: 'IAerodromeGauge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAerodromeGauge>
deployContract(name: 'IAerodromePair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAerodromePair>
deployContract(name: 'IAerodromeRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAerodromeRouter>
deployContract(name: 'IBuildingAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBuildingAdapter>
deployContract(name: 'IEntryPoint', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEntryPoint>
deployContract(name: 'IStakeManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakeManager>
deployContract(name: 'IMegapot', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMegapot>
deployContract(name: 'IMegapotReferral', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMegapotReferral>
deployContract(name: 'MockAavePool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAavePool>
deployContract(name: 'MockAerodromeGauge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAerodromeGauge>
deployContract(name: 'MockAerodromePair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAerodromePair>
deployContract(name: 'MockAerodromeRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAerodromeRouter>
deployContract(name: 'MockEntryPoint', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockEntryPoint>
deployContract(name: 'MockMegapot', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockMegapot>
deployContract(name: 'SmartWallet', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SmartWallet>

  deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'BankAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BankAdapter>
deployContract(name: 'LotteryAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LotteryAdapter>
deployContract(name: 'ShopAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ShopAdapter>
deployContract(name: 'BuildingRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BuildingRegistry>
deployContract(name: 'DefiCityCore', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DefiCityCore>
deployContract(name: 'WalletFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WalletFactory>
deployContract(name: 'IAToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAToken>
deployContract(name: 'IAavePool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAavePool>
deployContract(name: 'IAccount', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccount>
deployContract(name: 'IAccountExecute', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccountExecute>
deployContract(name: 'IAccountInitialize', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccountInitialize>
deployContract(name: 'IAerodromeGauge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAerodromeGauge>
deployContract(name: 'IAerodromePair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAerodromePair>
deployContract(name: 'IAerodromeRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAerodromeRouter>
deployContract(name: 'IBuildingAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBuildingAdapter>
deployContract(name: 'IEntryPoint', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEntryPoint>
deployContract(name: 'IStakeManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakeManager>
deployContract(name: 'IMegapot', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMegapot>
deployContract(name: 'IMegapotReferral', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMegapotReferral>
deployContract(name: 'MockAavePool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAavePool>
deployContract(name: 'MockAerodromeGauge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAerodromeGauge>
deployContract(name: 'MockAerodromePair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAerodromePair>
deployContract(name: 'MockAerodromeRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAerodromeRouter>
deployContract(name: 'MockEntryPoint', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockEntryPoint>
deployContract(name: 'MockMegapot', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockMegapot>
deployContract(name: 'SmartWallet', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SmartWallet>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  